schema_version: 1

context:
  name: ome-zarr-models
  version: "0.1.8"
  python_min: '3.11'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ome_zarr_models-${{ version }}.tar.gz
  sha256: cf5a0ffd7aa1d0ac7cdadaed589f0b1849c2528bada518dbfad7f5eb15025c02

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}
    - zarr <3
    - pydantic
    - pydantic-zarr

tests:
  - python:
      imports:
        - ome_zarr_models
      pip_check: true

      python_version: ${{ python_min }}.*
about:
  summary: A minimal Python package for reading OME-Zarr (meta)data
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/ome-zarr-models/ome-zarr-models-py

extra:
  recipe-maintainers:
    - imagejan
    - dstansby
    - d-v-b
