schema_version: 1

context:
  name: ome-zarr-models
  version: 0.1.5
  python_min: 3.11

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ome_zarr_models-${{ version }}.tar.gz
  sha256: cb82de1831f2eea48ff1827a467f3dff7698a131dbcfdc86fea1b9e93f1b73d4

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python 3.11.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}
    - zarr <3
    - pydantic
    - pydantic-zarr

tests:
  - python:
      imports:
        - ome_zarr_models
      pip_check: true

      python_version: ${{ python_min }}.*
about:
  summary: A minimal Python package for reading OME-Zarr (meta)data
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/ome-zarr-models/ome-zarr-models-py

extra:
  recipe-maintainers:
    - imagejan
    - dstansby
    - d-v-b
